import Head from 'next/head';
import Image from 'next/image';
import profile from '../public/profile-image.jpg';

export default function Index() {
  return (
    <div className='flex md:min-h-screen min-h-full flex-col items-center justify-center md:px-40 px-4'>
      <Head>
        <title>Home | Kingkin Fajar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex w-full flex-1 flex-col justify-center text-center'>

      <div className="grid md:grid-cols-3 items-center justify-center md:mb-0 md:mt-0 mt-8 mb-20">
        <div className='md:col-span-2 md:order-1 order-2 md:mt-0 mt-5 md:text-5xl text-4xl'>
          <h1 className='font-bold md:text-left text-center leading-tight'>Hi, I&apos;m <span className='text-green-400'>Kingkin Fajar</span> Developer and UI Design Enthusiast</h1>
        </div>
        <div className='md:w-72 md:h-72 w-48 h-w-48 rounded-full md:ml-auto mx-auto md:order-2 order-1'>
          <Image
            src={profile}
            width={600}
            height={600}
            className='object-cover h-full w-full rounded-full overflow-hidden'
          />
        </div>
      </div>
      </main>
    </div>
  );
}
