import Head from 'next/head';
import profile from '../public/profile-image.jpg';
import Image from 'next/image';

export default function Index() {
  return (
    <div className='flex md:min-h-screen min-h-full flex-col items-center justify-center md:px-40 px-4'>
      <Head>
        <title>Home | Kingkin Fajar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex w-full flex-1 flex-col justify-center text-center'>

      <div className="grid md:grid-cols-3 flex-col-reverse items-center justify-center md:mb-0 md:mt-0 mt-5 mb-20">
        <div className='md:col-span-2 md:order-1 order-2 md:mt-0 mt-5 md:text-5xl text-4xl'>
          <h1 className='font-bold md:text-left text-center leading-tight'>Hi, I'm <span className='text-green-400'>Kingkin Fajar</span> Developer and UI Design Enthusiast</h1>
        </div>
        <div className='md:w-72 md:h-72 w-48 h-w-48 rounded-full md:ml-auto mx-auto md:order-2 order-1'>
          <Image
            src={profile}
            width={600}
            height={600}
            className='object-cover h-full w-full rounded-full overflow-hidden'
          />
          {/* <img
            className="rounded-full md:h-full md:w-full h-40 w-40 md:ml-0 mx-auto md:mb-0 mb-6 overflow-hidden"
            src=""
            alt=""
          /> */}
        </div>
      </div>

        {/* <div className="md:flex items-center md:mt-14 md:mb-14 mb-5">
          <div className="">
            <img
              className="rounded-full md:h-80 md:w-80 h-40 w-40 md:mr-96 md:ml-0 mx-auto md:mb-0 mb-6"
              src="https://images.unsplash.com/photo-1646776172398-cfa4f022bc3a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwyfHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60"
              alt=""
            />
          </div>
          <div className="md:text-left text-center">
            <h1 className="font-bold md:text-3xl text-xl md:mb-7 mb-3 text-heading underline decoration-4 decoration-orange-500">
              Kingkin Fajar Anifianto &nbsp;
            </h1>
            <p className="mb-2 text-left">
              Passionate into programming since graduating from junior high school,
              Kingkin Fajar A (18) continues his study in vocational school with a
              software engineering major.
            </p>
            <p className="md:block text-left text-body">
              He's a front-end programmer specialized in a few programming languages
              such as PHP and Javascript, and also a few frameworks such as Laravel,
              React JS, and Next JS. Begin his portfolio by making Employee Attendance
              project, now he's done creating various projects.
            </p>
          </div>
        </div> */}
      </main>
    </div>
  );
}
